# @package _group_
experiment_params:
  name: 7scenes
  coprplusrelposeexp: False
  bs: 1
  n_workers: 8
  chosen_scene: 1
  datasetname: 7scenes #Cambridge or University or 7scenes or synthetic_shopfacade or relposefailure or station_escalator
  loss_type: distance #relativepose, triplet, distance
  stepsize: 0.05
  x_upsampling: 0.6
  y_upsampling: 1.4
  descriptors_stored: True
paths:
  datasets_home_dir: /media/mzaffar/extradata/datasets
  workdir: /home/mzaffar/Documents/codes/COPR_Retrieval_Test_Extrapolation
  snapshots_dir: ${paths.workdir}/models
  dataset_path: ${paths.datasets_home_dir}/7scenes/ #or station_escalator or  7scenes or Cambridge or University or synthetic_shopfacade or relposefailure or station_escalator
model_paramsCOPR:
  backbone_net: resnet34COPR
  features_dim: 512
  resume_snapshot: null
  snapshot: ${paths.snapshots_dir}/resnet34descregressor8linearlayers_resnet34_originalmodel_distanceloss1e4_ds507scenes_do0.0_7scenes_0.000550000/best_val.pth # resnet34descregressor8linearlayers_resnet34_originalmodel_station_escalator_v3_station_escalator_0.000550000 or resnet34descregressor8linearlayers_resnet34_originalmodel_ds207scenestriplet_1e_05_7scenes_0.000550000 or resnet34descregressor8linearlayers_resnet34_originalmodel_distanceloss1e4_ds507scenes_do0.0_synthetic_shopfacade_0.000550000 or resnet34descregressor8linearlayers_resnet34_originalmodel_syntheticshopfacade_train2m25cm_val2m100cm_do0.3synthetic_shopfacadedistance_0.0001_synthetic_shopfacade_0.000550000 or resnet34descregressor8linearlayers_resnet34_originalmodel_distanceloss1e4_ds507scenes_do0.0_synthetic_shopfacade_0.000550000 or resnet34descregressor8linearlayers_resnet34_originalmodel_ds507scenes_5e_05_syntheticshopfacade_train2m25cm_val2m100cm_do0.0_synthetic_shopfacade_0.000150000 or resnet34descregressor8linearlayers_resnet34_originalmodel_distanceloss1e4_ds507scenes_do0.0_7scenes_0.000550000 or resnet34descregressor8linearlayers_nonmixed_resnet34_originalmodel_ds507scenes_5e_05_7scenes_0.000550000 or resnet34descregressor8linearlayers_nonmixed_resnet34_originalmodel_ds20university_1e_05_University_1e_0550000 or resnet34descregressor8linearlayers_nonmixed_resnet34_originalmodel_ds50university_5e_05_University_0.000550000 or resnet34descregressor8linearlayers_nonmixed_resnet34_originalmodel_ds507scenes_5e_05_7scenes_0.000550000 or resnet34descregressor8linearlayers_resnet34_originalmodel_ds50University_5e_05_University_0.000550000 or resnet34descregressor8linearlayers_resnet34_originalmodel_ds507scenes_5e_05_7scenes_0.000550000 or resnet34descregressor8linearlayers_resnet34_originalmodel_newest3_mixed_University_0.000550000 resnet34descregressor8linearlayers_nonmixed_resnet34_originalmodel_ds507scenes_5e_05_7scenes_0 
model_paramsrelposenetorg:
  backbone_net: resnet34_originalmodel
  resume_snapshot: null
  snapshot: ${paths.snapshots_dir}/resnet34_originalmodel_ds507scenes_5e_05/best_val.pth #resnet34_originalmodel_syntheticshopfacade_train2m25cm_val2m100cm_do0.3synthetic_shopfacaderelativepose_5e_05 or resnet34_originalmodel_ds20University_1e_05 or resnet34_originalmodel_ds50University_5e_05 or resnet34_originalmodel_ds507scenes_5e_05 or resnet34_originalmodel_newest3_mixed_University_5e_05 or resnet34_originalmodel_newest_mixed_7scenes_5e_06
model_paramsrelposenettriplet:
  backbone_net: resnet34_originalmodel
  resume_snapshot: null
  snapshot: ${paths.snapshots_dir}/resnet34_originalmodel_ds207scenestriplet_1e_05/best_val.pth 
model_paramsrelposenetdistancebased:
  backbone_net: resnet34_originalmodel
  resume_snapshot: null
  snapshot: ${paths.snapshots_dir}/resnet34_originalmodel_ds207scenesdistance_0.0001/best_val.pth # resnet34_originalmodel_station_escalator_v3_station_escalatordistance_5e_05 or resnet34_originalmodel_syntheticshopfacade_train2m25cm_val2m100cm_do0.3synthetic_shopfacadedistance_0.0001 or resnet34_originalmodel_ds207scenesdistance_0.0001 or resnet34_originalmodel_ds20University_1e_05 or resnet34_originalmodel_ds50University_5e_05 or resnet34_originalmodel_ds507scenes_5e_05 or resnet34_originalmodel_newest3_mixed_University_5e_05 or resnet34_originalmodel_newest_mixed_7scenes_5e_06
  
  
#models used for T-RO paper#
#7scenes: resnet34_originalmodel_ds207scenesdistance_0.0001 and resnet34descregressor8linearlayers_resnet34_originalmodel_distanceloss1e4_ds507scenes_do0.0_7scenes_0.000550000
#station: resnet34descregressor8linearlayers_resnet34_originalmodel_station_escalator_v4_station_escalator_0.000550000 and resnet34_originalmodel_station_escalator_v4_station_escalatordistance_5e_05
#shopfacade: resnet34descregressor8linearlayers_resnet34_originalmodel_syntheticshopfacade_train2m25cm_val2m100cm_do0.3synthetic_shopfacadedistance_0.0001_synthetic_shopfacade_0.000550000 and resnet34_originalmodel_syntheticshopfacade_train2m25cm_val2m100cm_do0.3synthetic_shopfacadedistance_0.0001